name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
          

  Xcode:
    strategy:
      matrix:
        xcode_version: ['11.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v2
      - run: swift -version
      - run: ls /Applications | grep Xcode
      - run: swift package clean
      - run: swift test -v --enable-code-coverage
